### ISSUE TITLE
Tab bar scrolls off-screen

### ISSUE THREAD

**Issue by wrycode** [osa1/tiny#76]
This problem only occurs when I first start Tiny. Oddly enough, the tab bar behaves as expected after reconnecting to networks.

When I first start up Tiny, and it connects to my many channels on Freenode, the tab bar at the bottom of the screen appears to be broken. There is no ">" to denote more tabs. Instead, pressing Ctrl^n repeatedly scrolls me to tabs that I can no longer see, past the right edge of the screen.

However, after moving a few tabs past the right edge of the screen, the tab bar _does_ begin scrolling, only I still can't see the current tab I'm in, which should be visible and highlighted. As if Tiny thinks the terminal is wider than it is. Here are some screenshots:
This is before scrolling to a tab at the edge, viewing the ##linux channel
![realbeforescorlling](https://user-images.githubusercontent.com/34693012/34630968-48c26fc2-f23c-11e7-938d-fa75b83d109c.png)
Now I have scrolled to a tab that is halfway off the screen, #archlinux
![edge scrolling](https://user-images.githubusercontent.com/34693012/34630890-ff038c36-f23b-11e7-86af-8065f86de363.png)
Here I've scrolled past #archlinux and off the edge entirely.
![scrolling_past](https://user-images.githubusercontent.com/34693012/34630892-ff2b67d8-f23b-11e7-8f5f-43c3ac4f9851.png)
And here I've scrolled back, after scrolling forward for several more tabs. Notice that the tabs shifted, as if I did reach the edge of the screen before I scrolled back.
![scrolling back](https://user-images.githubusercontent.com/34693012/34630891-ff13a9d6-f23b-11e7-9496-ce25bee61ca5.png)
Finally, the tab bar behaves as expected once I reconnect to Freenode
![afterreconnect](https://user-images.githubusercontent.com/34693012/34631255-85e2e674-f23d-11e7-8812-c3344e6ffb2d.png)

**Comment by osa1** [comment]
Thanks for the detailed bug report.

Just to make sure, you're using the latest version from the git repo, correct?

I could not reproduce this. I checked the code just to see if there's something obvious but it looked fine. Disconnecting/reconnecting should have no effect on tab bar rendering so I think there's something else going on between the incorrect rendering and correcting it (e.g. a resize event from window manager).

I suspect that on initialization window size is somehow read wrong by termbox, and somehow updated before the reconnection.

Which window manager and terminal are you using?

If I'm right with my suspicion I think resizing the window after (or even before) running tiny should fix the issue. Could you try that?

Btw, there's an example program that I use to test tab bar rendering, you can run it using `cargo run --example tabs`. If you could reproduce the issue in that program that'd be easier to debug.

**Comment by wrycode** [comment]
I am getting this with the latest commit from upstream.

I am using the [i3](https://i3wm.org/) window manager, and [Termite](https://github.com/thestinger/termite) as my terminal emulator.
 
Resizing the terminal after or before launching Tiny does not fix it.

Running the example program, the tabs worked fine. I realized that this problem is only with the Freenode channels, I do not get this when only connecting to Mozilla.

**Comment by osa1** [comment]
This is so weird .. I realized a minor problem in the code and updated it, could you update your installation and try again? If it doesn't fix the issue, could you show us what `auto_cmds` you have in your `.tinyrc.yml` for freenode? I'll try to debug this with running the exact same list of commands.

**Comment by wrycode** [comment]
It's fixed! Sometimes the `>` doesn't show up when the tab doesn't fit perfectly at the right edge of the screen, but it's fine as soon as you scroll to that tab.

**Comment by osa1** [comment]
> Sometimes the > doesn't show up when the tab doesn't fit perfectly at the right edge of the screen

Can you give me names of tabs (with the order you see on the screen) when this happens? e.g. `mentions`, `chat.freenode.net`, `#python` ... the full list if possible.

**Comment by osa1** [comment]
Ping @wrycode

**Comment by wrycode** [comment]
This will do it:
`mentions irc.mozilla.org[i] #tiny[i] chat.freenode.net #test1 #test2 #test3 #test4`
Note that you'll have to make the terminal emulator pretty small to see this. For me I cut it off at #test3

![screenshot_2018-01-15_00-37-59](https://user-images.githubusercontent.com/34693012/34928567-78a303a8-f98c-11e7-97c8-0820566f015e.png)

**Comment by osa1** [comment]
Ah, you have ignore enabled. That makes sense. There's probably a bug in the code that generates width of a tab, it probably doesn't take `[i]` suffix into account. I'll fix this later today.

**Comment by osa1** [comment]
Thanks @wrycode, it should be fixed now.

**Comment by wrycode** [comment]
It is!
